/* tslint:disable */
/* eslint-disable */
/**
 * The «storage» service
 * storage service API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { FileRdo } from './file-rdo';

/**
 * 
 * @export
 * @interface FilesRdo
 */
export interface FilesRdo {
    /**
     * Total items count
     * @type {number}
     * @memberof FilesRdo
     */
    'count': number;
    /**
     * Total items count
     * @type {Array<FileRdo>}
     * @memberof FilesRdo
     */
    'items': Array<FileRdo>;
    /**
     * Limit the number of items
     * @type {number}
     * @memberof FilesRdo
     */
    'limit': number;
    /**
     * Skit the number of items
     * @type {number}
     * @memberof FilesRdo
     */
    'offset': number;
    /**
     * Page number
     * @type {number}
     * @memberof FilesRdo
     */
    'page': number;
    /**
     * Total number of pages
     * @type {number}
     * @memberof FilesRdo
     */
    'pages': number;
}

