/* tslint:disable */
/* eslint-disable */
/**
 * The «storage» service
 * storage service API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FileRdo
 */
export interface FileRdo {
    /**
     * File ID
     * @type {string}
     * @memberof FileRdo
     */
    'id': string;
    /**
     * Date of creation
     * @type {string}
     * @memberof FileRdo
     */
    'createdAt': string;
    /**
     * Hash name of the file
     * @type {string}
     * @memberof FileRdo
     */
    'hash': string;
    /**
     * Mime type of the file
     * @type {string}
     * @memberof FileRdo
     */
    'mimetype': string;
    /**
     * Extension of the file
     * @type {string}
     * @memberof FileRdo
     */
    'ext': string;
    /**
     * Name of the file
     * @type {string}
     * @memberof FileRdo
     */
    'name': string;
    /**
     * Path of file\'s dir
     * @type {string}
     * @memberof FileRdo
     */
    'path': string;
    /**
     * Path of the file
     * @type {string}
     * @memberof FileRdo
     */
    'src': string;
    /**
     * Size of the file in bytes
     * @type {number}
     * @memberof FileRdo
     */
    'size': number;
}

