/* tslint:disable */
/* eslint-disable */
/**
 * The «posts» service
 * posts service API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './clients/authors-api';
export * from './clients/comments-api';
export * from './clients/likes-api';
export * from './clients/posts-api';
export * from './clients/tags-api';

