###
# Вернуть список лайков
GET http://localhost:3001/api/likes HTTP/1.1

###
# Вернуть список лайков для postId
GET http://localhost:3001/api/likes?postId=ef837c5a-a953-11ee-817e-0242ac130002 HTTP/1.1

###
# Создать лайк к посту
POST http://localhost:3001/api/likes HTTP/1.1
Content-Type: application/json

{
  "authorId": "81074142-a950-11ee-93d5-0242ac130002",
  "postId": "ef837c5a-a953-11ee-817e-0242ac130002"
}

###
# Создать лайк к посту
POST http://localhost:3001/api/likes HTTP/1.1
Content-Type: application/json

{
  "userId": "6593d612e421b6051f1dd9c5",
  "postId": "ef837c5a-a953-11ee-817e-0242ac130002"
}

###
# Удалить лайк к посту
DELETE http://localhost:3001/api/likes HTTP/1.1
Content-Type: application/json

{
  "authorId": "81074142-a950-11ee-93d5-0242ac130002",
  "postId": "ef837c5a-a953-11ee-817e-0242ac130002"
}
