/* tslint:disable */
/* eslint-disable */
/**
 * The «users» service
 * users service API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthUserRdo
 */
export interface AuthUserRdo {
    /**
     * User ID
     * @type {string}
     * @memberof AuthUserRdo
     */
    'id': string;
    /**
     * Unique user email
     * @type {string}
     * @memberof AuthUserRdo
     */
    'email': string;
    /**
     * User access token
     * @type {string}
     * @memberof AuthUserRdo
     */
    'accessToken': string;
    /**
     * User refresh token
     * @type {string}
     * @memberof AuthUserRdo
     */
    'refreshToken': string;
}

