/* tslint:disable */
/* eslint-disable */
/**
 * The «users» service
 * users service API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdatePasswordDto
 */
export interface UpdatePasswordDto {
    /**
     * User password
     * @type {string}
     * @memberof UpdatePasswordDto
     */
    'password': string;
    /**
     * User new password
     * @type {string}
     * @memberof UpdatePasswordDto
     */
    'passwordNew': string;
}

