/* tslint:disable */
/* eslint-disable */
/**
 * The «users» service
 * users service API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserRdo
 */
export interface UserRdo {
    /**
     * User ID
     * @type {string}
     * @memberof UserRdo
     */
    'id': string;
    /**
     * Date of creation
     * @type {string}
     * @memberof UserRdo
     */
    'createdAt': string;
    /**
     * Unique user email
     * @type {string}
     * @memberof UserRdo
     */
    'email': string;
    /**
     * User firstname
     * @type {string}
     * @memberof UserRdo
     */
    'firstname': string;
    /**
     * User lastname
     * @type {string}
     * @memberof UserRdo
     */
    'lastname': string;
    /**
     * User avatar
     * @type {string}
     * @memberof UserRdo
     */
    'avatar': string;
}

