/* tslint:disable */
/* eslint-disable */
/**
 * The «users» service
 * users service API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UserRdo } from './user-rdo';

/**
 * 
 * @export
 * @interface UsersRdo
 */
export interface UsersRdo {
    /**
     * Total items count
     * @type {number}
     * @memberof UsersRdo
     */
    'count': number;
    /**
     * Total items count
     * @type {Array<UserRdo>}
     * @memberof UsersRdo
     */
    'items': Array<UserRdo>;
    /**
     * Limit the number of items
     * @type {number}
     * @memberof UsersRdo
     */
    'limit': number;
    /**
     * Skit the number of items
     * @type {number}
     * @memberof UsersRdo
     */
    'offset': number;
    /**
     * Page number
     * @type {number}
     * @memberof UsersRdo
     */
    'page': number;
    /**
     * Total number of pages
     * @type {number}
     * @memberof UsersRdo
     */
    'pages': number;
}

