###
# Зарегистрировать нового пользователя
POST http://localhost:3333/api/auth/singup HTTP/1.1
Content-Type: application/json

{
  "email": "keks@domain.com",
  "firstname": "keksik",
  "lastname": "keksikovich",
  "password": "password",
  "avatar": "avatar.jpg"
}

###
# Авторизовать пользователя
POST http://localhost:3333/api/auth/singin HTTP/1.1
Content-Type: application/json

{
  "email": "keks@domain.com",
  "password": "password"
}

###
# Ошибка авторизации пользователя
POST http://localhost:3333/api/auth/singin HTTP/1.1
Content-Type: application/json

{
  "email": "keks@domain.com",
  "password": "1234567"
}

###
# Вернуть текущего авторизованного пользователя (в заголовке передаем accessToken)
GET http://localhost:3333/api/auth/user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YWQ2OTM2MDQwMWEwMTg4YmM0NDJhMiIsImVtYWlsIjoia2Vrc0Bkb21haW4uY29tIiwiaWF0IjoxNzA1ODYzNzU4LCJleHAiOjE3MDU4NjQwNTh9.XwzP1br8E-JP0EnhF0KRsWlH_uk10eFj6RqEngdGV5k

###
# Вернуть новый токен (в заголовке передаем refreshToken)
POST http://localhost:3333/api/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YWQ2OTM2MDQwMWEwMTg4YmM0NDJhMiIsImVtYWlsIjoia2Vrc0Bkb21haW4uY29tIiwidG9rZW5JZCI6ImY2MGZlZmE0LWQwY2EtNGExZi05OTExLTc4MzI4YzBlY2UxNSIsImlhdCI6MTcwNTg2MzUwOCwiZXhwIjoxNzA4NDU1NTA4fQ.MWvz4nAcoRuX5Z0RSGlxAbzzCvd7QbTpfNes2UrIQu8

###
# Изменить пароль авторизованного пользователя
PATCH http://localhost:3333/api/auth/user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YWQ2OTM2MDQwMWEwMTg4YmM0NDJhMiIsImVtYWlsIjoia2Vrc0Bkb21haW4uY29tIiwiaWF0IjoxNzA1ODY0NDA5LCJleHAiOjE3MDU4NjQ3MDl9.KQ42R4UXmawelbC6vdKKgYa8PfFjwrpWpnXruAlfm6A
Content-Type: application/json

{
  "password": "password",
  "passwordNew": "password"
}
