###
# Зарегистрировать пользователя
POST http://localhost:3333/api/auth/singup HTTP/1.1
Content-Type: application/json

{
  "email": "keks@domain.com",
  "firstname": "keksik",
  "lastname": "keksikovich",
  "password": "password",
  "avatar": "avatar.jpg"
}

###
# Ошибка авторизации пользователя
POST http://localhost:3333/api/auth/singin HTTP/1.1
Content-Type: application/json

{
  "email": "keks@domain.com",
  "password": "1234567"
}

###
# Авторизовать пользователя
POST http://localhost:3333/api/auth/singin HTTP/1.1
Content-Type: application/json

{
  "email": "bob@domain.com",
  "password": "password"
}

###
# Вернуть текущего авторизованного пользователя
GET http://localhost:3333/api/auth HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OTJmMDg5N2FmZjdhM2UzYmM0ZDE3MyIsImVtYWlsIjoiYm9iQGRvbWFpbi5jb20iLCJpYXQiOjE3MDQ0NTM1ODYsImV4cCI6MzQwODgzOTE5OX0.nACfVYt6Chl_hWokkEbkMyY9MKmLxMGDjxbAavfAaGc

###
# Изменить пароль авторизованного пользователя
PATCH http://localhost:3333/api/auth HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OTJmMDg5N2FmZjdhM2UzYmM0ZDE3MyIsImVtYWlsIjoiYm9iQGRvbWFpbi5jb20iLCJpYXQiOjE3MDQ0NTM1ODYsImV4cCI6MzQwODgzOTE5OX0.nACfVYt6Chl_hWokkEbkMyY9MKmLxMGDjxbAavfAaGc
Content-Type: application/json

{
  "password": "password",
  "passwordNew": "password1"
}
