###
# Регистрация нового пользователя
POST http://localhost:3004/api/auth/singup HTTP/1.1
Content-Type: application/json

{
  "email": "keksidar@domain.com",
  "firstname": "keksik",
  "lastname": "keksikovich",
  "password": "password",
  "avatar": "avatar.jpg"
}

###
# Регистрация доступна только анонимным клиентам
# данный запрос должен вернуть 403 Forbidden
POST http://localhost:3004/api/auth/singup HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YWQ3NWU0NDY5MWVkOGRlN2FkMmQ5ZCIsImVtYWlsIjoia2Vrc0Bkb21haW4uY29tIiwiaWF0IjoxNzA2MzUxODkwLCJleHAiOjE3MDYzNTIxOTB9.3XnOYUVP2VumO4m7yhAtXM2T6MUuuwuR4wpZooJfM1k
Content-Type: application/json

{
  "email": "keksos@domain.com",
  "firstname": "keksik",
  "lastname": "keksikovich",
  "password": "password",
  "avatar": "avatar.jpg"
}

###
# Авторизовать пользователя
POST http://localhost:3004/api/auth/singin HTTP/1.1
Content-Type: application/json

{
  "email": "keksidar@domain.com",
  "password": "password"
}

###
# Ошибка авторизации пользователя
POST http://localhost:3004/api/auth/singin HTTP/1.1
Content-Type: application/json

{
  "email": "keksidar@domain.com",
  "password": "1234567"
}

###
# Вернуть текущего авторизованного пользователя (в заголовке передаем accessToken)
GET http://localhost:3004/api/auth/user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YjRlMmUwODUwMzBmMzg2YTU2MTk1YyIsImVtYWlsIjoia2Vrc2lkYXJAZG9tYWluLmNvbSIsImlhdCI6MTcwNjM4MTgzMCwiZXhwIjoxNzA2MzgyMTMwfQ.opPyqJMNo3nl9wE1l6wxbioTyo2CYrgQDHUvah-TwZg

###
# Вернуть новый токен (в заголовке передаем refreshToken)
POST http://localhost:3004/api/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YWQ2OTM2MDQwMWEwMTg4YmM0NDJhMiIsImVtYWlsIjoia2Vrc0Bkb21haW4uY29tIiwidG9rZW5JZCI6ImY2MGZlZmE0LWQwY2EtNGExZi05OTExLTc4MzI4YzBlY2UxNSIsImlhdCI6MTcwNTg2MzUwOCwiZXhwIjoxNzA4NDU1NTA4fQ.MWvz4nAcoRuX5Z0RSGlxAbzzCvd7QbTpfNes2UrIQu8

###
# Изменить пароль авторизованного пользователя
PATCH http://localhost:3004/api/auth/user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YjRlMmUwODUwMzBmMzg2YTU2MTk1YyIsImVtYWlsIjoia2Vrc2lkYXJAZG9tYWluLmNvbSIsImlhdCI6MTcwNjM1Mzk4MiwiZXhwIjoxNzA2MzU0MjgyfQ.Yduh5djmLFKQKoQjyg1MpAZmHKG0IOB3BlLEkWRAlwI
Content-Type: application/json

{
  "password": "password1",
  "passwordNew": "password"
}
