/* tslint:disable */
/* eslint-disable */
/**
 * The «posts» service
 * posts service API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthorRdo
 */
export interface AuthorRdo {
    /**
     * Author ID
     * @type {string}
     * @memberof AuthorRdo
     */
    'id': string;
    /**
     * Date of creation
     * @type {string}
     * @memberof AuthorRdo
     */
    'createdAt': string;
    /**
     * Author\'s comments count
     * @type {number}
     * @memberof AuthorRdo
     */
    'countComments': number;
    /**
     * Author\'s posts count
     * @type {number}
     * @memberof AuthorRdo
     */
    'countPosts': number;
    /**
     * Author\'s likes count
     * @type {number}
     * @memberof AuthorRdo
     */
    'countLikes': number;
}

