/* tslint:disable */
/* eslint-disable */
/**
 * The «posts» service
 * posts service API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommentRdo
 */
export interface CommentRdo {
    /**
     * Comment ID
     * @type {string}
     * @memberof CommentRdo
     */
    'id': string;
    /**
     * Date of creation
     * @type {string}
     * @memberof CommentRdo
     */
    'createdAt': string;
    /**
     * Date of updating
     * @type {string}
     * @memberof CommentRdo
     */
    'updatedAt': string;
    /**
     * The ID of the author of the comment
     * @type {string}
     * @memberof CommentRdo
     */
    'authorId': string;
    /**
     * The ID of the post of the comment
     * @type {string}
     * @memberof CommentRdo
     */
    'postId': string;
    /**
     * The message of the comment
     * @type {string}
     * @memberof CommentRdo
     */
    'message': string;
}

