/* tslint:disable */
/* eslint-disable */
/**
 * The «posts» service
 * posts service API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CommentRdo } from './comment-rdo';

/**
 * 
 * @export
 * @interface CommentsRdo
 */
export interface CommentsRdo {
    /**
     * Total items count
     * @type {number}
     * @memberof CommentsRdo
     */
    'count': number;
    /**
     * Total items count
     * @type {Array<CommentRdo>}
     * @memberof CommentsRdo
     */
    'items': Array<CommentRdo>;
    /**
     * Limit the number of items
     * @type {number}
     * @memberof CommentsRdo
     */
    'limit': number;
    /**
     * Skit the number of items
     * @type {number}
     * @memberof CommentsRdo
     */
    'offset': number;
    /**
     * Page number
     * @type {number}
     * @memberof CommentsRdo
     */
    'page': number;
    /**
     * Total number of pages
     * @type {number}
     * @memberof CommentsRdo
     */
    'pages': number;
}

