/* tslint:disable */
/* eslint-disable */
/**
 * The «posts» service
 * posts service API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateLikeDto
 */
export interface CreateLikeDto {
    /**
     * The ID of the author of the like
     * @type {string}
     * @memberof CreateLikeDto
     */
    'authorId': string;
    /**
     * The ID of the post of the like
     * @type {string}
     * @memberof CreateLikeDto
     */
    'postId': string;
}

