/* tslint:disable */
/* eslint-disable */
/**
 * The «posts» service
 * posts service API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const PostsOrder = {
    PublishAt: 'PUBLISH_AT',
    Likes: 'LIKES',
    Comments: 'COMMENTS'
} as const;

export type PostsOrder = typeof PostsOrder[keyof typeof PostsOrder];



