/* tslint:disable */
/* eslint-disable */
/**
 * The «posts» service
 * posts service API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RemovePostDto
 */
export interface RemovePostDto {
    /**
     * Post\'s author id
     * @type {string}
     * @memberof RemovePostDto
     */
    'authorId'?: string;
}

