/* tslint:disable */
/* eslint-disable */
/**
 * The «posts» service
 * posts service API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TagRdo
 */
export interface TagRdo {
    /**
     * Tag ID
     * @type {string}
     * @memberof TagRdo
     */
    'id': string;
    /**
     * Date of creation
     * @type {string}
     * @memberof TagRdo
     */
    'createdAt': string;
    /**
     * Date of updating
     * @type {string}
     * @memberof TagRdo
     */
    'updatedAt': string;
    /**
     * Text of the tag
     * @type {string}
     * @memberof TagRdo
     */
    'text': string;
}

