/* tslint:disable */
/* eslint-disable */
/**
 * The «posts» service
 * posts service API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PostType } from './post-type';

/**
 * 
 * @export
 * @interface UpdatePostDto
 */
export interface UpdatePostDto {
    /**
     * Post\'s author id
     * @type {string}
     * @memberof UpdatePostDto
     */
    'authorId'?: string;
    /**
     * 
     * @type {PostType}
     * @memberof UpdatePostDto
     */
    'postType': PostType;
    /**
     * Post\'s payload
     * @type {object}
     * @memberof UpdatePostDto
     */
    'payload': object;
}



